version: "3"

services:
  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
        - "8080:80"
    volumes:
        - ./conf.d:/etc/nginx/conf.d
        - ./html:/usr/share/nginx/html
