version: "3"

services:
  server:
    image: gogs/gogs:0.12.3
    container_name: gogs
    restart: always
    volumes:
      - ./gogs:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "10080:3000"
      - "10022:22"
